version: '3.8'

services:
  frontend:
    build: ./path-to-astro-project
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./path-to-spring-boot-project
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/website
      - SPRING_DATASOURCE_USERNAME=web
      - SPRING_DATASOURCE_PASSWORD=webAdmin0
    depends_on:
      - database
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: web
      POSTGRES_PASSWORD: webAdmin0

    volumes: 
    - postgres-data:/var/lib/postgresql/data 

volumes: 
  postgres-data: